### ISSUE TITLE
Inconsistent styling on printed pages

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/frontend#947] opened 2016-04-26 12:54 UTC
If users print with native print (command-p) vs using 'print entire guide' function, the result is inconsistent.

I suspect some styling is missing from the 'print entire guide' function. It has far smaller font sizes and has serif fonts in places.

Native print:
![screen shot 2016-04-26 at 13 52 32](https://cloud.githubusercontent.com/assets/2204224/14818687/5f33e2f4-0bb6-11e6-8d39-524588eada1e.png)

Print entire guide:
![screen shot 2016-04-26 at 13 52 17](https://cloud.githubusercontent.com/assets/2204224/14818699/6796c3c6-0bb6-11e6-9606-cff97045a5bf.png)

**Comment by andysellick** [comment] 2017-05-23 13:25
@edwardhorsford is this issue still occurring? Can't reproduce and page styles seem to have changed since.

**Comment by nickcolley** [comment] 2017-05-23 13:27
This is fixed by the merging of multipage and guides 👍 

Thanks for raising @edwardhorsford

**Closed by nickcolley** 2017-05-23 13:27 UTC
